branches:
  only:
    - master
    - develop
language: node_js
node_js: '10'
cache: npm
before_install:
  - npm i -g npm@latest
script:
  - npm run lint
  - npm run test
after_success:
  - npm run storybook:build
notifications:
  email:
    on_success: never
    on_failure: always